"""
    Copyright(C) 2018 Jacek Łysiak

    Constants used by OMTFInputPipe.
"""


class PIPE_MAPPING_TYPE:
    INTERLEAVE = 0
    FLAT_MAP = 1
    
 
class PIPE_OUT_DATA:
    EXTRA_OMTF_PT_CLASS = "OMTF_PT_CLASS"
    EXTRA_OMTF_PT_VAL = "OMTF_PT_VAL"
    EXTRA_OMTF_SGN_CLASS = "OMTF_SIGN_CLASS"
    EXTRA_PROD_PT_CODE = "PT_CODE"
    EXTRA_PROD_PT_VAL = "PROD_PT_VAL"
    EXTRA_PROD_PT_CLASS = "PROD_PT_CLASS"
    TRAIN_PROD_PT = "PROD_PT_LABEL"
    TRAIN_PROD_SGN = "PROD_SGN_CLASS"

